### ISSUE TITLE
My documents are not being indexed

### ISSUE THREAD

**Issue by aminobj** [Azure/GPT-RAG#107]
Trying to run this and my PDF files don't seem to be indexed by the search service. Do I need to somehow kick it off?
This needs better documentation.

**Comment by imartinez2** [comment]
Hi, in my case, yesterday at 10 PM (UTC-4) , executed a deployment of the solution, and the index, indexer, and skillset of the Azure AI Search were not configured, by the deployment, I deleted all, and executed the deployment at 1 AM (UTC-4) and all was create ok and running without problem

**Comment by aminobj** [comment]
Did you delete everything in the resource group before re-deployment or just search service, AI etc.?

**Comment by imartinez2** [comment]
Yes, I delete all, resource group and resources.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aminobj** [comment]
Just to be clear, you deleted everything and ran `azd deploy` instead of `azd up` right?
Not sure what difference it makes if everything is deleted but want to reproduce exactly what you did.
It doesn't seem to help me when I just delete and re-up everything.

**Comment by imartinez2** [comment]
I delete all, azure and local folder and do all as new.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aminobj** [comment]
Didn't help me :(

**Comment by loopdeloop76** [comment]
Hi, I have the same problem. I uploaded a PDF to a Storage account in the gpt-rag resource group, but it is not imported into the ragindex of the Search service.
My `azd up` deployment was successful, but I do not see any services such as `dataIngest` or `orchestrator` in my rg-gpt-rag resource group.

**Comment by mmossmic** [comment]
Hi, could you fix the problem?
I try to redeploy after deleting all (resource group and resources) and still have the same issue after uploading the documents.

**Comment by aminobj** [comment]
Personally, I think this is an abandoned project.
Just try this one.
https://github.com/Azure-Samples/azure-search-openai-demo

It seems to be a fork (or closely related) project and worked for me.
