### ISSUE TITLE
Issue# Data Ingest: Encripted Documents

### ISSUE THREAD

**Issue by rogiorda** [Azure/GPT-RAG#17]
Open and index encripted documents with AIP

**Comment by gbecerra1982** [comment]
Work in Progress:
Just as reference
https://learn.microsoft.com/en-us/azure/search/search-security-trimming-for-azure-search-with-aad

**Comment by gbecerra1982** [comment]
To utilize Form Recognizer on documents that are encrypted with Azure Information Protection, you would first need to decrypt the documents. Here are the general steps:

Identify the type of encryption/protection: Ensure that the files are encrypted or protected with Azure Information Protection.

Use Azure Information Protection SDK: Microsoft provides an SDK that can be used to programmatically decrypt files protected with AIP.

Here is an example of how you might use the SDK to decrypt a file:

csharp
Copy code
var stream = new FileStream(encryptedFilePath, FileMode.Open, FileAccess.Read);
var authDelegate = new AuthDelegateImplementation();
var engine = new FileEngine(appPrincipalId, tenantId, authDelegate);
var decryptedFilePath = engine.Unprotect(stream);
This code opens the encrypted file, authenticates with Azure using your application's principal ID and tenant ID, and then decrypts the file. Unprotect() returns a FileStream object that points to the decrypted file.

Note that you'll need to implement AuthDelegateImplementation. It's a class that implements IAuthDelegate, and its purpose is to acquire an access token.

Send the decrypted files to Form Recognizer: After the files are decrypted, you can then send them to Form Recognizer for processing. For instance:

csharp
Copy code
using var formClient = new FormRecognizerClient(new Uri(endpoint), new AzureKeyCredential(apiKey));
using var stream = new FileStream(decryptedFilePath, FileMode.Open);
var form = await formClient.StartRecognizeContent(stream).WaitForCompletionAsync();
This code opens the decrypted file, sends it to Form Recognizer, and gets the recognized form data.

Remember that as you handle sensitive and/or encrypted data, you should always adhere to best practices for data security and privacy. Don't decrypt data that you don't have permission to decrypt, and don't leave decrypted data lying around where it might be accessed by unauthorized individuals.

Also, this process may differ based on changes in the Azure platform or their SDKs after my knowledge cutoff in September 2021. Always refer to the most recent documentation for the most accurate and up-to-date information.

Lastly, please consult with your organization's security team to ensure the method you're using adheres to your organization's security and compliance policies.

**Comment by gbecerra1982** [comment]
Who the data ingest function impersonate to decrypt files?

Create Application Registration and add API Permissions to Azure Information Protection. 

![image](https://github.com/Azure/GPT-RAG/assets/6539041/8a9fd569-1ff6-4e20-b2b8-c61eca05ceeb)
