### ISSUE TITLE
Set BICEP Key vault enableSoftDelete to false

### ISSUE THREAD

**Issue by pradorodriguez** [Azure/GPT-RAG#170]
Recommendation: Set BICEP Key vault enableSoftDelete to false
Why: If customer wants to redeploy, newer deployments will fail due to the existence of soft deleted Key Vaults.
BICEP: https://learn.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults?pivots=deployment-language-bicep#vaultproperties
Parameter: enableSoftDelete

**Comment by scottroot-msft** [comment]
in the meantime...as a workaround, during the deprovisioning, you can encourage users to run: `azd down --force --purge` which should take care of anything marked for soft-deletion without intervention.

**Comment by placerda** [comment]
Many customers have "Key vaults should have soft delete enabled" policy, causing errors if we set this false.

https://learn.microsoft.com/en-us/azure/defender-for-cloud/policy-reference#security-centers-default-initiative-azure-security-benchmark
