### ISSUE TITLE
The subnet does not conform to the Network Security Group (NSG) requirements during the creation of the virtual network (VNet).

### ISSUE THREAD

**Issue by SaravanansrinivasanAIfactory** [Azure/GPT-RAG#205]
We are attempting to deploy Zero Trust Architecture (ZTA) for one of our customers. However, the subnet being created as part of the deployment is not associated with a Network Security Group (NSG), causing the deployment to fail. Please refer to the attached error message for more details.
<img width="931" alt="image (1) 2" src="https://github.com/user-attachments/assets/a6f87e06-98b6-483f-813c-f3c3f1f27797">

Hi @placerda @gbecerra1982 please advise.

**Comment by placerda** [comment]
Fixed:
https://github.com/Azure/GPT-RAG/pull/217
