### ISSUE TITLE
Bug - DNS is not registered Correctly in Bicep

### ISSUE THREAD

**Issue by gbecerra1982** [Azure/GPT-RAG#33]
privatelink.search.windows.net | search.windows.net

**Comment by misantibanez** [comment]
standard2 for searchServiceSkuName required to request a quota increase, error message: "Operation would exceed 'standard2' tier service quota. You are using 0 out of 0 'standard2' tier service quota. If you need more quota, please submit a quota increase request with issue type 'Service and subscription limits (quota)' and quota type 'Search' following https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-quota-errors. (Code: ServiceQuotaExceeded) "

I fixed it by replacing standard2 for standard in main.bicep file.

var searchServiceSkuName = networkIsolation?'standard':'standard'
