### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jucastag** [Azure/GPT-RAG#58]
Recibo el siguiente mensaje al utilizar la app: Lo siento, yo tuve un problema con la solicitud. Por favor informe el error al equipo de soporte. SyntaxError: Unexpected end of JSON input.

Realice deploy desde cero de los 3 repositorios - Ingestion - Orchestrator - Frontend

webapp log stream:
[Log_stream.txt](https://github.com/Azure/GPT-RAG/files/13048423/Log_stream.txt)

**Comment by jucastag** [comment]
Updates: Error message in orchestrator log stream  live metrics: 

Exception while executing function: Functions.orc <--- Result: Failure Exception: CosmosHttpResponseError: (Forbidden) Request blocked by Auth dbgpt0mbpzj : Request is blocked because principal [cb546dbfc7a] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]. Learn more: https://aka.ms/cosmos-native-rbac. ActivityId: 55d4b201, Microsoft.Azure.Documents.Common/2.14.0 Code: Forbidden Message: Request blocked by Auth dbgpt0mbpzj : Request is blocked because principal [cb8dbfc7a] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]. Learn more: https://aka.ms/cosmos-native-rbac. ActivityId: b91d35d4b201, Microsoft.Azure.Documents.Common/2.14.0 Stack: File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 493, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 762, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/orc/__init__.py", line 28, in main result = orchestrator.run(conversation_id, question, client_principal) File "/home/site/wwwroot/orc/orchestrator.py", line 44, in run db_client = CosmosClient(AZURE_DB_URI, credential, consistency_level='Session') File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/cosmos_client.py", line 190, in __init__ self.client_connection = CosmosClientConnection( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/_cosmos_client_connection.py", line 210, in __init__ database_account = self._global_endpoint_manager._GetDatabaseAccount(**kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/_global_endpoint_manager.py", line 124, in _GetDatabaseAccount database_account = self._GetDatabaseAccountStub(self.DefaultEndpoint, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/_global_endpoint_manager.py", line 147, in _GetDatabaseAccountStub return self.Client.GetDatabaseAccount(endpoint, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/_cosmos_client_connection.py", line 2122, in GetDatabaseAccount result, self.last_response_headers = self.__Get("", request_params, headers, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/_cosmos_client_connection.py", line 2316, in __Get return synchronized_request.SynchronizedRequest( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/_synchronized_request.py", line 206, in SynchronizedRequest return _retry_utility.Execute( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/_retry_utility.py", line 83, in Execute result = ExecuteFunction(function, global_endpoint_manager, *args, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/_retry_utility.py", line 143, in ExecuteFunction return function(*args, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmos/_synchronized_request.py", line 154, in _Request raise exceptions.CosmosHttpResponseError(message=data, response=response)

**Comment by jucastag** [comment]
Aparently an issue with cosmoDB. Will close the issue if I solve it.

**Comment by jucastag** [comment]
Solved.. A new "deplot to azure" was needed.

**Comment by bgawale** [comment]
@jucastag can you please share steps how did you manage to fix it? I'm facing the same issue after completing all steps of deployment from ingestion till front end. 

![image](https://github.com/Azure/GPT-RAG/assets/47916356/ee2d40ed-0450-4358-868c-3153618d055d)
