### ISSUE TITLE
710.000 USD per month ? 

### ISSUE THREAD

**Issue by garethjax** [Azure/GPT-RAG#91]
As per title. 

It seems a tiny expensive.

**Comment by maacaro** [comment]
yes tiny expensive

**Comment by gbecerra1982** [comment]
Hi, there is an issue with the Azure Calculator that we will be fixing this week. 

The cost for the Non Zero Trust is around 1.2k and Zero Trust version 5k Monthly.

**Comment by gbecerra1982** [comment]
The calculator was fixed: 
https://azure.com/e/269be04781da41ed98fa5225be221f61

The pricing of the GPT Models in the pricing calculator is outdated, it will be updated soon.
